using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Abstractions.TestingHelpers;
using System.Linq;
using System.Threading.Tasks;
using LanguageExt;
using Moq;
using NUnit.Framework;
using SJP.Schematic.Core;
using SJP.Schematic.Core.Comments;
using SJP.Schematic.Tests.Utilities;

namespace SJP.Schematic.DataAccess.Poco.Tests;

[TestFixture]
internal static class PocoDataAccessGeneratorTests
{
    private const string TestCsprojFileName = "DataAccessGeneratorTest.csproj";

    private static IIdentifierDefaults IdentifierDefaults => new IdentifierDefaults("a", "b", "c");

    [Test]
    public static void Ctor_GivenNullFileSystem_ThrowsArgumentNullException()
    {
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        Assert.That(() => new PocoDataAccessGenerator(null, database, commentProvider, nameTranslator), Throws.ArgumentNullException);
    }

    [Test]
    public static void Ctor_GivenNullDatabase_ThrowsArgumentNullException()
    {
        var mockFs = new MockFileSystem();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        Assert.That(() => new PocoDataAccessGenerator(mockFs, null, commentProvider, nameTranslator), Throws.ArgumentNullException);
    }

    [Test]
    public static void Ctor_GivenNullCommentProvider_ThrowsArgumentNullException()
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var nameTranslator = new VerbatimNameTranslator();
        Assert.That(() => new PocoDataAccessGenerator(mockFs, database, null, nameTranslator), Throws.ArgumentNullException);
    }

    [Test]
    public static void Ctor_GivenNullNameTranslator_ThrowsArgumentNullException()
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        Assert.That(() => new PocoDataAccessGenerator(mockFs, database, commentProvider, null), Throws.ArgumentNullException);
    }

    [TestCase((string)null)]
    [TestCase("")]
    [TestCase("    ")]
    public static void GenerateAsync_GivenNullProjectPath_ThrowsArgumentException(string projectPath)
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new PocoDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);

        Assert.That(() => generator.GenerateAsync(projectPath, "test"), Throws.InstanceOf<ArgumentException>());
    }

    [TestCase((string)null)]
    [TestCase("")]
    [TestCase("    ")]
    public static void GenerateAsync_GivenNullOrWhiteSpaceNamespace_ThrowsArgumentException(string ns)
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new PocoDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, TestCsprojFileName);

        Assert.That(() => generator.GenerateAsync(projectPath, ns), Throws.InstanceOf<ArgumentException>());
    }

    [Test]
    public static async Task GenerateAsync_GivenStaleFilesFromPreviousRun_RemovesStaleFilesAndKeepsCurrentFiles()
    {
        var mockFs = new MockFileSystem();
        var database = CreateDatabase(["current_table"], ["current_view"]);
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new PocoDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, TestCsprojFileName);

        var staleTablePath = Path.Combine(tempDir.DirectoryPath, "Tables", "dropped_table.cs");
        var staleViewPath = Path.Combine(tempDir.DirectoryPath, "Views", "old_schema", "dropped_view.cs");
        mockFs.AddFile(staleTablePath, new MockFileData("// generated by a previous run"));
        mockFs.AddFile(staleViewPath, new MockFileData("// generated by a previous run"));

        await generator.GenerateAsync(projectPath, "test");

        var currentTablePath = Path.Combine(tempDir.DirectoryPath, "Tables", "current_table.cs");
        var currentViewPath = Path.Combine(tempDir.DirectoryPath, "Views", "current_view.cs");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(mockFs.File.Exists(staleTablePath), Is.False);
            Assert.That(mockFs.File.Exists(staleViewPath), Is.False);
            Assert.That(mockFs.File.Exists(currentTablePath), Is.True);
            Assert.That(mockFs.File.Exists(currentViewPath), Is.True);
        }
    }

    [Test]
    public static void GenerateAsync_GivenProjectPathNotACsproj_ThrowsArgumentException()
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new PocoDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, "DataAccessGeneratorTest.vbproj");

        Assert.That(() => generator.GenerateAsync(projectPath, "test"), Throws.ArgumentException);
    }

    [Test]
    public static async Task GenerateAsync_GivenTablesTranslatingToTheSameClassName_GeneratesDistinctlyNamedFiles()
    {
        var mockFs = new MockFileSystem();
        var database = CreateDatabase(["first second", "firstsecond"], []);
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new PocoDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, TestCsprojFileName);

        await generator.GenerateAsync(projectPath, "test");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(mockFs.File.Exists(Path.Combine(tempDir.DirectoryPath, "Tables", "firstsecond.cs")), Is.True);
            Assert.That(mockFs.File.Exists(Path.Combine(tempDir.DirectoryPath, "Tables", "firstsecond_1.cs")), Is.True);
        }
    }

    [Test]
    public static async Task GenerateAsync_GivenTableAndViewTranslatingToTheSameClassName_GeneratesDistinctlyNamedClasses()
    {
        var mockFs = new MockFileSystem();
        var database = CreateDatabase(["shared_name"], ["shared_name"]);
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new PocoDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, TestCsprojFileName);

        await generator.GenerateAsync(projectPath, "test");

        var tablePath = Path.Combine(tempDir.DirectoryPath, "Tables", "shared_name.cs");
        var viewPath = Path.Combine(tempDir.DirectoryPath, "Views", "shared_name_1.cs");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(mockFs.File.ReadAllText(tablePath), Does.Contain("record shared_name"));
            Assert.That(mockFs.File.ReadAllText(viewPath), Does.Contain("record shared_name_1"));
        }
    }

    [Test]
    public static async Task GenerateAsync_GivenTablesTranslatingToClassNamesDifferingOnlyByCase_GeneratesDistinctlyNamedFiles()
    {
        var mockFs = new MockFileSystem();
        var database = CreateDatabase(["test_table", "TEST_TABLE"], []);
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new PocoDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, TestCsprojFileName);

        await generator.GenerateAsync(projectPath, "test");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(mockFs.File.Exists(Path.Combine(tempDir.DirectoryPath, "Tables", "test_table.cs")), Is.True);
            Assert.That(mockFs.File.Exists(Path.Combine(tempDir.DirectoryPath, "Tables", "TEST_TABLE_1.cs")), Is.True);
        }
    }

    [Test]
    public static async Task GenerateAsync_GivenTablesWithTheSameNameInDifferentSchemas_GeneratesBothTables()
    {
        var mockFs = new MockFileSystem();
        var database = CreateDatabase([Identifier.CreateQualifiedIdentifier("first", "test_table"), Identifier.CreateQualifiedIdentifier("second", "test_table")], []);
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new PocoDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, TestCsprojFileName);

        await generator.GenerateAsync(projectPath, "test");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(mockFs.File.Exists(Path.Combine(tempDir.DirectoryPath, "Tables", "first", "test_table.cs")), Is.True);
            Assert.That(mockFs.File.Exists(Path.Combine(tempDir.DirectoryPath, "Tables", "second", "test_table.cs")), Is.True);
        }
    }

    private static IRelationalDatabase CreateDatabase(IEnumerable<Identifier> tableNames, IEnumerable<Identifier> viewNames)
    {
        var tables = tableNames
            .Select(static tableName => new RelationalDatabaseTable(tableName, [], Option<IDatabaseKey>.None, [], [], [], [], [], []))
            .ToList<IRelationalDatabaseTable>();
        var views = viewNames
            .Select(static viewName => new DatabaseView(viewName, "select 1 as dummy", []))
            .ToList<IDatabaseView>();

        return new RelationalDatabase(
            IdentifierDefaults,
            new VerbatimIdentifierResolutionStrategy(),
            tables,
            views,
            [],
            [],
            []
        );
    }
}