version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
- package-ecosystem: npm
  directory: "/src/SJP.Schematic.Reporting"
  schedule:
    interval: daily
  versioning-strategy: increase
  open-pull-requests-limit: 50
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
