language: csharp
dotnet: 6.0.100
mono: none
matrix:
  include:
    - os: linux
      dist: bionic
      before_install:
        - nvm use 11
        - sudo apt-get -qq update && sudo apt-get install -y graphviz
        - sudo apt-get --yes remove postgresql\*
        - sudo apt-get install -y postgresql-12 postgresql-client-12
        - node --version
        - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
        - sudo service postgresql restart 12
      addons:
        postgresql: "12"
      services:
        - mysql
        - postgresql
      env:
        - ConnectionStrings__MySql_TestDb="Server=localhost; Port=3306; Database=schematic; Uid=root; ConnectionTimeout=2"
        - PGPORT=5433
        - PGUSER=postgres
        - ConnectionStrings__PostgreSql_TestDb="Server=localhost; Port=5433; Database=schematic; User Id=postgres; Timeout=2"
        - ConnectionStrings__PostgreSql_TestDb_12="Server=localhost; Port=5433; Database=schematic; User Id=postgres; Timeout=2"
      before_script:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS schematic;'
        - psql -c 'create database schematic;' -U postgres
    # disable OSX as it times out installing dependencies, should work regardless    
    #- os: osx
    #  addons:
    #    homebrew:
    #      update: true
    #      packages:
    #        - node
    #        - graphviz
script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet tool install -g Cake.Tool --version 0.37.0
  - dotnet cake build.cake
  - dotnet cake build.cake --target=Run-Unit-Tests
  # enable doc building when docfx v3 is available
  # as it will be implemented as a dotnet tool
  #- dotnet cake build.cake --target=Build-Docs
