version: 1.0.{build}
image: Visual Studio 2022

install:
  - cmd: dotnet --info
  - cmd: node --version
  - ps: Install-Product node $env:nodejs_version

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

environment:
  nodejs_version: "13"
  MYSQL_PWD: Password12!
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\12
  ConnectionStrings__MySql_TestDb: Server=localhost; Port=3306; Database=schematic; Uid=root; Pwd=Password12!; ConnectionTimeout=2
  ConnectionStrings__PostgreSql_TestDb: Server=localhost; Port=5432; Database=schematic; User Id=postgres; Password=Password12!; Timeout=2
  ConnectionStrings__PostgreSql_TestDb_12: Server=localhost; Port=5432; Database=schematic; User Id=postgres; Password=Password12!; Timeout=2
  ConnectionStrings__SqlServer_TestDb: Server=(local)\SQL2019; Database=master; User ID=sa; Password=Password12!; MultipleActiveResultSets=true; Connection Timeout=2
  ConnectionStrings__SqlServer_TestDb_2017: Server=(local)\SQL2017; Database=master; User ID=sa; Password=Password12!; MultipleActiveResultSets=true; Connection Timeout=2
  ConnectionStrings__SqlServer_TestDb_2019: Server=(local)\SQL2019; Database=master; User ID=sa; Password=Password12!; MultipleActiveResultSets=true; Connection Timeout=2

init:
  - net start MSSQL$SQL2019
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%
  - ps: >-
      Get-ChildItem -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\' |
      Where-Object {
          $_.Name -imatch 'MSSQL[_\d]+\.SQL.*';
      } |
      ForEach-Object {
          Write-Host "Setting $((Get-ItemProperty $_.PSPath).'(default)') to dynamic ports";
          Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpDynamicPorts -Value '0';
          Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpPort -Value ([string]::Empty);
      }

services:
  - mssql2017
  - postgresql12
  - mysql

build_script:
  - mysql -e "create database schematic;" --user=root
  - createdb schematic
  - ps: ./build.ps1

test_script:
  - ps: ./build.ps1 -Target Run-Unit-Tests

after_test:
  - ps: ./build.ps1 -Target Build-Docs

notifications:
- provider: Email
  to:
    - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
