<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Generate DBML files for use with dbdiagram.io</Description>
    <PackageTags>$(PackageTags);dbml;dbdiagram;erd;diagram</PackageTags>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SJP.Schematic.Core\SJP.Schematic.Core.csproj" />
  </ItemGroup>

</Project>
