using System;
using System.IO;
using System.IO.Abstractions.TestingHelpers;
using System.Threading.Tasks;
using LanguageExt;
using Moq;
using NUnit.Framework;
using SJP.Schematic.Core;
using SJP.Schematic.Core.Comments;
using SJP.Schematic.Tests.Utilities;

namespace SJP.Schematic.DataAccess.OrmLite.Tests;

[TestFixture]
internal static class OrmLiteDataAccessGeneratorTests
{
    private const string TestCsprojFileName = "DataAccessGeneratorTest.csproj";

    private static IIdentifierDefaults IdentifierDefaults => new IdentifierDefaults("a", "b", "c");

    [Test]
    public static void Ctor_GivenNullFileSystem_ThrowsArgumentNullException()
    {
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var database = Mock.Of<IRelationalDatabase>();
        var nameTranslator = new VerbatimNameTranslator();

        Assert.That(() => new OrmLiteDataAccessGenerator(null, database, commentProvider, nameTranslator), Throws.ArgumentNullException);
    }

    [Test]
    public static void Ctor_GivenNullDatabase_ThrowsArgumentNullException()
    {
        var mockFs = new MockFileSystem();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();

        Assert.That(() => new OrmLiteDataAccessGenerator(mockFs, null, commentProvider, nameTranslator), Throws.ArgumentNullException);
    }

    [Test]
    public static void Ctor_GivenNullCommentProvider_ThrowsArgumentNullException()
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var nameTranslator = new VerbatimNameTranslator();

        Assert.That(() => new OrmLiteDataAccessGenerator(mockFs, database, null, nameTranslator), Throws.ArgumentNullException);
    }

    [Test]
    public static void Ctor_GivenNullNameTranslator_ThrowsArgumentNullException()
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);

        Assert.That(() => new OrmLiteDataAccessGenerator(mockFs, database, commentProvider, null), Throws.ArgumentNullException);
    }

    [TestCase((string)null)]
    [TestCase("")]
    [TestCase("    ")]
    public static void GenerateAsync_GivenNullOrWhiteSpaceProjectPath_ThrowsArgumentException(string projectPath)
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new OrmLiteDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);

        Assert.That(() => generator.GenerateAsync(projectPath, "test"), Throws.InstanceOf<ArgumentException>());
    }

    [TestCase((string)null)]
    [TestCase("")]
    [TestCase("    ")]
    public static void GenerateAsync_GivenNullOrWhiteSpaceNamespace_ThrowsArgumentException(string ns)
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new OrmLiteDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, TestCsprojFileName);

        Assert.That(() => generator.GenerateAsync(projectPath, ns), Throws.InstanceOf<ArgumentException>());
    }

    [Test]
    public static async Task GenerateAsync_GivenStaleFilesFromPreviousRun_RemovesStaleFilesAndKeepsCurrentFiles()
    {
        var mockFs = new MockFileSystem();
        var database = CreateDatabase("current_table", "current_view");
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new OrmLiteDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, TestCsprojFileName);

        var staleTablePath = Path.Combine(tempDir.DirectoryPath, "Tables", "dropped_table.cs");
        var staleViewPath = Path.Combine(tempDir.DirectoryPath, "Views", "old_schema", "dropped_view.cs");
        mockFs.AddFile(staleTablePath, new MockFileData("// generated by a previous run"));
        mockFs.AddFile(staleViewPath, new MockFileData("// generated by a previous run"));

        await generator.GenerateAsync(projectPath, "test");

        var currentTablePath = Path.Combine(tempDir.DirectoryPath, "Tables", "current_table.cs");
        var currentViewPath = Path.Combine(tempDir.DirectoryPath, "Views", "current_view.cs");
        Assert.Multiple(() =>
        {
            Assert.That(mockFs.File.Exists(staleTablePath), Is.False);
            Assert.That(mockFs.File.Exists(staleViewPath), Is.False);
            Assert.That(mockFs.File.Exists(currentTablePath), Is.True);
            Assert.That(mockFs.File.Exists(currentViewPath), Is.True);
        });
    }

    [Test]
    public static void GenerateAsync_GivenProjectPathNotACsproj_ThrowsArgumentException()
    {
        var mockFs = new MockFileSystem();
        var database = Mock.Of<IRelationalDatabase>();
        var commentProvider = new EmptyRelationalDatabaseCommentProvider(IdentifierDefaults);
        var nameTranslator = new VerbatimNameTranslator();
        var generator = new OrmLiteDataAccessGenerator(mockFs, database, commentProvider, nameTranslator);
        using var tempDir = new TemporaryDirectory();
        var projectPath = Path.Combine(tempDir.DirectoryPath, "DataAccessGeneratorTest.vbproj");

        Assert.That(() => generator.GenerateAsync(projectPath, "test"), Throws.ArgumentException);
    }

    private static IRelationalDatabase CreateDatabase(Identifier tableName, Identifier viewName)
    {
        var table = new RelationalDatabaseTable(tableName, [], Option<IDatabaseKey>.None, [], [], [], [], [], []);
        var view = new DatabaseView(viewName, "select 1 as dummy", []);

        return new RelationalDatabase(
            IdentifierDefaults,
            new VerbatimIdentifierResolutionStrategy(),
            [table],
            [view],
            [],
            [],
            []
        );
    }
}