using SJP.Schematic.Core;

namespace SJP.Schematic.Oracle
{
    /// <summary>
    /// Defines additional information available on Oracle databases.
    /// </summary>
    /// <seealso cref="IDatabaseIndex" />
    public interface IOracleDatabaseIndex : IDatabaseIndex
    {
        /// <summary>
        /// Determines whether the index was automatically generated by a constraint.
        /// </summary>
        /// <value><c>true</c> if the index was generated by a constraint; otherwise, <c>false</c>.</value>
        bool GeneratedByConstraint { get; }
    }
}