using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using EnumsNET;
using LanguageExt;

namespace SJP.Schematic.Core;

/// <summary>
/// A description of what a database engine is able to express.
/// </summary>
/// <remarks>
/// Every capability defaults to the conservative answer, i.e. that the engine lacks the feature, so
/// a dialect only declares what it can do. <see cref="SupportedReferentialActions"/> and
/// <see cref="MaxIdentifierLength"/> have no conservative answer and must always be given.
/// </remarks>
/// <seealso cref="IDatabaseDialectCapabilities" />
public sealed record DatabaseDialectCapabilities : IDatabaseDialectCapabilities
{
    /// <summary>
    /// Indicates whether objects are organised into named schemas, i.e. whether a schema forms part
    /// of an object's qualified name. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsSchemas { get; init; }

    /// <summary>
    /// Indicates whether the engine has sequences. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsSequences { get; init; }

    /// <summary>
    /// Indicates whether the engine has synonyms, i.e. alternative names for other objects. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsSynonyms { get; init; }

    /// <summary>
    /// Indicates whether the engine has stored routines, i.e. functions or procedures. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsRoutines { get; init; }

    /// <summary>
    /// Indicates whether the engine has materialized views, i.e. views whose results are stored. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsMaterializedViews { get; init; }

    /// <summary>
    /// Indicates whether the engine can store comments describing database objects. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsComments { get; init; }

    /// <summary>
    /// Indicates whether constraint checking can be deferred to the end of a transaction. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsDeferrableConstraints { get; init; }

    /// <summary>
    /// Indicates whether an index can be restricted to a subset of a table's rows. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsFilteredIndexes { get; init; }

    /// <summary>
    /// Indicates whether an index can carry non-key columns stored only to satisfy a query. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsIncludedIndexColumns { get; init; }

    /// <summary>
    /// Indicates whether a column's value can be computed from an expression. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsComputedColumns { get; init; }

    /// <summary>
    /// Indicates whether a column's value can be generated by the engine on insert. The default is <see langword="false" />.
    /// </summary>
    public bool SupportsIdentityColumns { get; init; }

    /// <summary>
    /// The referential actions that the engine is able to apply to a foreign key.
    /// </summary>
    /// <exception cref="ArgumentNullException">The given set is <see langword="null" />.</exception>
    /// <exception cref="ArgumentException">The given set contains a value that is not a valid enum, or omits <see cref="ReferentialAction.NoAction"/>.</exception>
    public required IReadOnlySet<ReferentialAction> SupportedReferentialActions
    {
        get => _supportedReferentialActions;
        init
        {
            ArgumentNullException.ThrowIfNull(value);
            if (value.Any(static a => !a.IsValid()))
                throw new ArgumentException($"The {nameof(ReferentialAction)} values provided must all be valid enums.", nameof(value));
            if (!value.Contains(ReferentialAction.NoAction))
                throw new ArgumentException($"The supported referential actions must contain {nameof(ReferentialAction.NoAction)}, which every engine is able to express.", nameof(value));

            _supportedReferentialActions = value.ToFrozenSet();
        }
    }

    /// <summary>
    /// The table that must be selected from when a query has no table of its own, e.g. <c>DUAL</c>.
    /// The default is <see cref="Option{A}.None"/>, i.e. no table is required.
    /// </summary>
    public Option<string> FromLessSelectSuffix { get; init; }

    /// <summary>
    /// The greatest number of characters an identifier may contain, or <see cref="int.MaxValue"/>
    /// when the engine imposes no practical limit.
    /// </summary>
    /// <exception cref="ArgumentOutOfRangeException">The given length is zero or negative.</exception>
    public required int MaxIdentifierLength
    {
        get => _maxIdentifierLength;
        init
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(value);
            _maxIdentifierLength = value;
        }
    }

    private readonly IReadOnlySet<ReferentialAction> _supportedReferentialActions = FrozenSet<ReferentialAction>.Empty;

    private readonly int _maxIdentifierLength = 1;
}
