using System.Collections.Generic;
using LanguageExt;

namespace SJP.Schematic.Core;

/// <summary>
/// Describes what a database engine is able to express, so that consumers can adapt to a dialect
/// without probing a live connection or switching on a vendor name.
/// </summary>
/// <remarks>
/// A capability describes the engine, not a particular database. It says whether an engine can have
/// an object or a feature at all, never whether a given database uses one. Where an engine's answer
/// depends on its version, a dialect reports the answer for the oldest version Schematic supports
/// querying, because a dialect is stateless and has no connection to interrogate.
/// </remarks>
public interface IDatabaseDialectCapabilities
{
    /// <summary>
    /// Indicates whether objects are organised into named schemas, i.e. whether a schema forms part
    /// of an object's qualified name.
    /// </summary>
    /// <value><see langword="true" /> if objects are schema-qualified; otherwise, <see langword="false" />.</value>
    bool SupportsSchemas { get; }

    /// <summary>
    /// Indicates whether the engine has sequences.
    /// </summary>
    /// <value><see langword="true" /> if sequences are available; otherwise, <see langword="false" />.</value>
    bool SupportsSequences { get; }

    /// <summary>
    /// Indicates whether the engine has synonyms, i.e. alternative names for other objects.
    /// </summary>
    /// <value><see langword="true" /> if synonyms are available; otherwise, <see langword="false" />.</value>
    bool SupportsSynonyms { get; }

    /// <summary>
    /// Indicates whether the engine has stored routines, i.e. functions or procedures.
    /// </summary>
    /// <value><see langword="true" /> if routines are available; otherwise, <see langword="false" />.</value>
    bool SupportsRoutines { get; }

    /// <summary>
    /// Indicates whether the engine has materialized views, i.e. views whose results are stored.
    /// </summary>
    /// <value><see langword="true" /> if materialized views are available; otherwise, <see langword="false" />.</value>
    bool SupportsMaterializedViews { get; }

    /// <summary>
    /// Indicates whether the engine can store comments describing database objects.
    /// </summary>
    /// <value><see langword="true" /> if object comments are available; otherwise, <see langword="false" />.</value>
    bool SupportsComments { get; }

    /// <summary>
    /// Indicates whether constraint checking can be deferred to the end of a transaction.
    /// </summary>
    /// <value><see langword="true" /> if deferrable constraints are available; otherwise, <see langword="false" />.</value>
    bool SupportsDeferrableConstraints { get; }

    /// <summary>
    /// Indicates whether an index can be restricted to a subset of a table's rows, e.g. a
    /// filtered or partial index.
    /// </summary>
    /// <value><see langword="true" /> if filtered indexes are available; otherwise, <see langword="false" />.</value>
    bool SupportsFilteredIndexes { get; }

    /// <summary>
    /// Indicates whether an index can carry non-key columns that are stored only to satisfy a
    /// query, e.g. an <c>INCLUDE</c> clause.
    /// </summary>
    /// <value><see langword="true" /> if included index columns are available; otherwise, <see langword="false" />.</value>
    bool SupportsIncludedIndexColumns { get; }

    /// <summary>
    /// Indicates whether a column's value can be computed from an expression.
    /// </summary>
    /// <value><see langword="true" /> if computed columns are available; otherwise, <see langword="false" />.</value>
    bool SupportsComputedColumns { get; }

    /// <summary>
    /// Indicates whether a column's value can be generated by the engine on insert, e.g. an
    /// identity or auto-increment column.
    /// </summary>
    /// <value><see langword="true" /> if identity columns are available; otherwise, <see langword="false" />.</value>
    bool SupportsIdentityColumns { get; }

    /// <summary>
    /// The referential actions that the engine is able to apply to a foreign key.
    /// </summary>
    /// <value>A set of supported referential actions.</value>
    /// <remarks>
    /// An action outside this set is either rejected by the engine or accepted and then treated as
    /// another action. <see cref="ReferentialAction.NoAction"/> is always present, as it describes
    /// the absence of an action as much as a declared one.
    /// </remarks>
    IReadOnlySet<ReferentialAction> SupportedReferentialActions { get; }

    /// <summary>
    /// The table that must be selected from when a query has no table of its own, e.g. <c>DUAL</c>.
    /// </summary>
    /// <value>
    /// <see cref="Option{A}.None"/> when the engine accepts a <c>SELECT</c> without a <c>FROM</c> clause;
    /// otherwise the name to append to <c>from</c>.
    /// </value>
    Option<string> FromLessSelectSuffix { get; }

    /// <summary>
    /// The greatest number of characters an identifier may contain.
    /// </summary>
    /// <value>The maximum identifier length, or <see cref="int.MaxValue"/> when the engine imposes no practical limit.</value>
    int MaxIdentifierLength { get; }
}
