using LanguageExt;

namespace SJP.Schematic.Core;

/// <summary>
/// Represents a database column present on a table or view.
/// </summary>
public interface IDatabaseColumn
{
    /// <summary>
    /// The name of a column within a table or view.
    /// </summary>
    /// <value>A column name.</value>
    Identifier Name { get; }

    /// <summary>
    /// Determines whether a column can store <see langword="null" /> values.
    /// </summary>
    /// <value><see langword="true" /> if this column can store <see langword="null" /> values; otherwise, <see langword="false" />.</value>
    bool IsNullable { get; }

    /// <summary>
    /// Determines whether the values of this column are generated by the database.
    /// </summary>
    /// <value><see langword="true" /> if the values within this column are computed by the database; otherwise, <see langword="false" />.</value>
    bool IsComputed { get; }

    /// <summary>
    /// The default applied to a column when omitted on an <c>INSERT</c> statement, including the
    /// name of the constraint carrying it and a classification of what its expression evaluates to.
    /// </summary>
    /// <value>The default for a column, if available.</value>
    Option<IDatabaseDefaultValue> Default { get; }

    /// <summary>
    /// An expression that creates a default value for a column when omitted on an <c>INSERT</c> statement.
    /// A convenience over <see cref="Default"/>, which carries the same expression alongside the
    /// constraint name and classification.
    /// </summary>
    /// <value>The default value for a column, if available.</value>
    Option<string> DefaultValue => Default.Map(static def => def.Definition);

    /// <summary>
    /// The database column data type.
    /// </summary>
    /// <value>A column data type.
    /// </value>
    IDbType Type { get; }

    /// <summary>
    /// Retrieves the auto-increment parameters applies to this column, if available.
    /// </summary>
    /// <value>An automatic increment definition, if available.
    /// </value>
    Option<IAutoIncrement> AutoIncrement { get; }

    /// <summary>
    /// The expression that computes the values of this column. Always <see cref="Option{A}.None"/>
    /// when <see cref="IsComputed"/> is <see langword="false" />, and optional otherwise as some
    /// providers (e.g. Oracle) allow the definition to be missing.
    /// </summary>
    /// <value>A computed column definition, if available.</value>
    Option<string> ComputedDefinition { get; }

    /// <summary>
    /// Determines whether the computed values of this column are stored in the table or evaluated
    /// when the column is read. Always <see cref="ComputedColumnStorage.Unknown"/> when
    /// <see cref="IsComputed"/> is <see langword="false" />.
    /// </summary>
    /// <value>The storage applied to a computed column.</value>
    ComputedColumnStorage ComputedStorage { get; }
}