namespace SJP.Schematic.Core;

/// <summary>
/// Describes how a database generates the values of an auto-incrementing column, in particular
/// whether a value provided by an <c>INSERT</c> statement is accepted or rejected.
/// </summary>
public enum IdentityGeneration
{
    /// <summary>
    /// The generation strategy is not known, either because the database does not report one,
    /// or because it is a strategy that this enumeration does not describe.
    /// </summary>
    Unknown,

    /// <summary>
    /// The database generates a value only when the <c>INSERT</c> statement does not supply one,
    /// i.e. PostgreSQL <c>GENERATED BY DEFAULT AS IDENTITY</c>, MySQL <c>AUTO_INCREMENT</c>,
    /// SQLite <c>AUTOINCREMENT</c> and rowid aliases, and SQL Server <c>IDENTITY</c>.
    /// </summary>
    ByDefault,

    /// <summary>
    /// The database generates a value when the <c>INSERT</c> statement does not supply one, or
    /// supplies <c>NULL</c>, i.e. Oracle <c>GENERATED BY DEFAULT ON NULL AS IDENTITY</c>.
    /// </summary>
    ByDefaultOnNull,

    /// <summary>
    /// The database always generates the value, and rejects one supplied by an <c>INSERT</c>
    /// statement, i.e. PostgreSQL and Oracle <c>GENERATED ALWAYS AS IDENTITY</c>.
    /// </summary>
    Always,
}
