name: docfx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: windows-latest

    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: install docfx
      # specifying 2.58.5 version as latest release (2.58.8) has an issue
      # https://github.com/dotnet/docfx/issues/7689
      run: choco install docfx -y --version=2.58.5

    - name: build doc metadata
      working-directory: docs
      run: docfx metadata

    - name: build docs
      working-directory: docs
      run: docfx docfx.json
