name: docfx

permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v5

    - name: install docfx
      run: dotnet tool update -g docfx

    - name: build doc metadata
      working-directory: docs
      run: docfx metadata

    - name: build docs
      working-directory: docs
      run: docfx docfx.json
