name: dotnet format

on:
  push:
    branches: [ master ]
    paths:
    - '**.cs'
    - 'src/.editorconfig'
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - 'src/.editorconfig'

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: dotnet format
      run: dotnet format --verify-no-changes
      working-directory: src