name: pack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore
      working-directory: src

    - name: Pack
      run: dotnet pack --configuration Release --no-restore
      working-directory: src
