name: postgres

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  db:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [10, 11, 12, 13, 14, 15, 16, 17, latest]
    services:
      postgres:
        image: postgres:${{ matrix.tag }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/SJP.Schematic.PostgreSql.Tests

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/SJP.Schematic.PostgreSql.Tests

    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: src/SJP.Schematic.PostgreSql.Tests
      env:
        ConnectionStrings__PostgreSql_TestDb: Server=localhost; Port=5432; Database=postgres; User Id=postgres; Password=postgres; Timeout=2

    - name: Coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
