name: sql-server
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  db:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [2017-latest, 2019-latest, 2022-latest, latest]
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:${{ matrix.tag }}
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: Schematic0123!
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Schematic0123!' -Q 'SELECT 1' || exit 1"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 10
          --health-start-period 10s
        ports:
          - 1433:1433
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/SJP.Schematic.SqlServer.Tests

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/SJP.Schematic.SqlServer.Tests

    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: src/SJP.Schematic.SqlServer.Tests
      env:
        ConnectionStrings__SqlServer_TestDb: Data Source=localhost,1433; User Id=sa; Password=Schematic0123!; MultipleActiveResultSets=True; TrustServerCertificate=True;

    - name: Coverage
      uses: codecov/codecov-action@v4
